spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/financial?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: America/Sao_Paulo
    open-in-view: true

  flyway:
    enabled: false
  docker:
    compose:
      enabled: false
server:
  port: 8080
