services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=financialms'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
